version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
  db:
    image: postgres:14.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=my_project
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
