version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=My_project
      - POSTGRES_HOST=db
    ports: 
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    
  redis:
    image: "redis:7.0.11"
    ports:
      - "6379"

volumes:
  postgres_data:
